-- ============================================================================
-- SUPABASE DATABASE SCHEMA FOR ML TRADING SYSTEM
-- ============================================================================

-- ML Models table
-- Stores metadata for all production-ready models
CREATE TABLE IF NOT EXISTS ml_models (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    model_path TEXT NOT NULL,
    features JSONB NOT NULL,
    num_features INTEGER NOT NULL,
    parameters JSONB NOT NULL,
    backtest_results JSONB NOT NULL,
    win_rate DECIMAL(5,2),
    profit_factor DECIMAL(5,2),
    sharpe_ratio DECIMAL(5,2),
    max_drawdown DECIMAL(5,2),
    total_trades INTEGER,
    status TEXT DEFAULT 'production_ready',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(symbol, timeframe)
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_ml_models_symbol_tf ON ml_models(symbol, timeframe);
CREATE INDEX IF NOT EXISTS idx_ml_models_status ON ml_models(status);

-- Live signals table
-- Stores real-time trading signals generated by models
CREATE TABLE IF NOT EXISTS live_signals (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    model_id UUID REFERENCES ml_models(id) ON DELETE CASCADE,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    signal_type TEXT NOT NULL, -- 'long', 'short', 'flat'
    confidence DECIMAL(5,4),
    edge DECIMAL(5,4),
    entry_price DECIMAL(12,5),
    stop_loss DECIMAL(12,5),
    take_profit DECIMAL(12,5),
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'active', -- 'active', 'closed', 'expired'
    expires_at TIMESTAMPTZ
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_live_signals_symbol ON live_signals(symbol);
CREATE INDEX IF NOT EXISTS idx_live_signals_status ON live_signals(status);
CREATE INDEX IF NOT EXISTS idx_live_signals_timestamp ON live_signals(timestamp DESC);

-- Trades table
-- Stores all executed trades with entry/exit details
CREATE TABLE IF NOT EXISTS trades (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    signal_id UUID REFERENCES live_signals(id) ON DELETE SET NULL,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    direction TEXT NOT NULL, -- 'long', 'short'
    entry_time TIMESTAMPTZ,
    entry_price DECIMAL(12,5),
    exit_time TIMESTAMPTZ,
    exit_price DECIMAL(12,5),
    stop_loss DECIMAL(12,5),
    take_profit DECIMAL(12,5),
    pnl DECIMAL(12,2),
    pnl_pct DECIMAL(8,4),
    r_multiple DECIMAL(6,2),
    exit_reason TEXT, -- 'tp', 'sl', 'timeout', 'manual'
    status TEXT DEFAULT 'open', -- 'open', 'closed'
    bars_held INTEGER,
    confidence DECIMAL(5,4),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
CREATE INDEX IF NOT EXISTS idx_trades_status ON trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_entry_time ON trades(entry_time DESC);
CREATE INDEX IF NOT EXISTS idx_trades_pnl ON trades(pnl);

-- Performance metrics table
-- Aggregated performance metrics updated periodically
CREATE TABLE IF NOT EXISTS performance_metrics (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    period TEXT NOT NULL, -- 'daily', 'weekly', 'monthly', 'all_time'
    total_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    win_rate DECIMAL(5,2),
    profit_factor DECIMAL(5,2),
    total_pnl DECIMAL(12,2),
    avg_win DECIMAL(10,2),
    avg_loss DECIMAL(10,2),
    max_win DECIMAL(10,2),
    max_loss DECIMAL(10,2),
    avg_r_multiple DECIMAL(6,2),
    sharpe_ratio DECIMAL(5,2),
    max_drawdown DECIMAL(5,2),
    period_start TIMESTAMPTZ,
    period_end TIMESTAMPTZ,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(symbol, timeframe, period, period_start)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_perf_metrics_symbol_tf ON performance_metrics(symbol, timeframe);
CREATE INDEX IF NOT EXISTS idx_perf_metrics_period ON performance_metrics(period);

-- Create storage bucket for ONNX models
-- Run this separately in Supabase Storage UI or via API
-- INSERT INTO storage.buckets (id, name, public) 
-- VALUES ('ml_models', 'ml_models', true)
-- ON CONFLICT (id) DO NOTHING;

-- Enable Row Level Security (RLS) for production
ALTER TABLE ml_models ENABLE ROW LEVEL SECURITY;
ALTER TABLE live_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE performance_metrics ENABLE ROW LEVEL SECURITY;

-- Create policies (allow read access to authenticated users, modify later as needed)
CREATE POLICY "Allow read access to ml_models" ON ml_models FOR SELECT USING (true);
CREATE POLICY "Allow read access to live_signals" ON live_signals FOR SELECT USING (true);
CREATE POLICY "Allow read access to trades" ON trades FOR SELECT USING (true);
CREATE POLICY "Allow read access to performance_metrics" ON performance_metrics FOR SELECT USING (true);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for updated_at
CREATE TRIGGER update_ml_models_updated_at BEFORE UPDATE ON ml_models
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_trades_updated_at BEFORE UPDATE ON trades
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_performance_metrics_updated_at BEFORE UPDATE ON performance_metrics
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- DONE! Now you can sync your models to Supabase
-- ============================================================================

